### ISSUE TITLE
Found 0 valid plots -> chia  plots check -g xxx

### ISSUE THREAD

**Issue by mech2you** [Chia-Network/bladebit#296]
Testet with switch -compress 0 and without... Plots are not valid. 

 .\bladebit_cuda.exe -n 100 -t 24 --compress 0 -f XXX -c XXX cudaplot G:\Chia

source bladebit_cuda.exe -> https://downloads.chia.net/bladebit/

Bladebit Chia Plotter
Version      : 3.0.0-alpha1-dev
Git Commit   : f269db0a7ad307514e993c335897cea7ebf46eda
Compiled With: msvc 19.33.31630

System:
3960x 256GB RAM 3060 12GB

![image](https://user-images.githubusercontent.com/61209759/221383644-8606bdd9-8ada-4b3e-8cde-c9425bccef0c.png)

**Comment by kinomexanik** [comment]
chia gui sees plots? My farm sees plots and farms. 
bladebit_cuda.exe -n 1 --compress 0 -f -c cudaplot H:\
The -t parameter is not needed.

**Comment by harold-b** [comment]
It is currently a known bug on Windows. It will yield bad plots. Fix is pending for next release

**Comment by mech2you** [comment]
> It is currently a known bug on Windows. It will yield bad plots. Fix is pending for next release

Thx for the information. Is there a schedule for the next onenext release

**Comment by kinomexanik** [comment]
made 70tb of plots, and it turns out in vain. does not send proofs of the pool.

**Comment by Sonix1** [comment]
Just deleted 400+ plots created by bladebit_cuda. The GUI reported no problems, the number of plots increased but pool payouts stayed the same. Only the chia plots check showed that the plots were incorrect. It's a pity that you wrote so late that the problem is known.

**Comment by harold-b** [comment]
There's a beta/alpha keybase channel, where all the info is being shared (for those who signed up). It was shared there a while back. It would be good to keep an eye there for the latest info.

Regardless of which, it's a good idea to check all the plots until after out of beta, even if it's checking with a low `-n` count.

**Comment by harold-b** [comment]
There's a beta/alpha keybase channel, where all the info is being shared (for those who signed up). It was shared there a while back. It would be good to keep an eye there for the latest info.

Regardless of which, it's a good idea to check all the plots until after out of beta, even if it's checking with a low `-n` count.

**Comment by kinomexanik** [comment]
bladebit-cuda-v3.0.0-alpha2 
who installed? fixed on the proofs?

**Comment by mech2you** [comment]
> bladebit-cuda-v3.0.0-alpha2 who installed? fixed on the proofs?

Yesterday i checkt it with two plots. Version [ae066d3](https://github.com/Chia-Network/bladebit/commit/ae066d3ddff3392f0fd55867040639922a3d4418) and it not work on windows. Compiled at VS 2022

**Comment by kinomexanik** [comment]
sad( I waited so long, but alas... I'm going to cry

**Comment by kinomexanik** [comment]
ubuntu 22.04 bladebit_cuda alpha1 plots is good! 
alpha2 error cuda(

**Comment by lokus77** [comment]
Ubuntu 22.1  bladebit_cuda alpha1 OK. Plots are valid.
Ubuntu 22.1  bladebit_cuda alpha2 does not start plotting:  CUDA error: 13 (0xd ) cudaErrorInvalidSymbol : invalid device symbol
Ubuntu 22.1  bladebit_cuda alpha3 does not start plotting:  CUDA error: 13 (0xd ) cudaErrorInvalidSymbol : invalid device symbol
--.
Windows 10  bladebit_cuda alpha1 plots are invalid
Windows 10  bladebit_cuda **alpha3** plots are invalid

**Comment by corymiranda** [comment]
CUDA error: 13 (0xd ) cudaErrorInvalidSymbol : invalid device symbol

Update to CUDA 12.1 to resolve this issue.

**Comment by mech2you** [comment]
3.0.0-alpha3-dev on win10x64 plot not valid
![image](https://user-images.githubusercontent.com/61209759/224576184-9d2ab9ce-0a13-4018-81c8-24966d6e21e2.png)

**Comment by kinomexanik** [comment]
I get sad when I see that plots are not valid in Windows

**Comment by harold-b** [comment]
Me too. But it's being worked on. I can't currently reproduce it as  they come out valid in my windows machine. Will need a bit of a deeper dive.

**Comment by harold-b** [comment]
> 3.0.0-alpha3-dev on win10x64 plot not valid

To confirm: These plots were made also with **3.0.0-alpha3-dev **?

**Comment by lokus77** [comment]
> > 3.0.0-alpha3-dev on win10x64 plot not valid
> 
> To confirm: These plots were made also with _**3.0.0-alpha3-dev**_?

Yes, I used https://download.chia.net/bladebit/bladebit_cuda-windows-alpha3.exe
 and "chia plots check" always says is invalid

**Comment by mech2you** [comment]
`
Bladebit Chia Plotter
Version      : 3.0.0-alpha3-dev
Git Commit   : eb6df030b555fb35addc3d6762424d52826a5d82
Compiled With: msvc 19.33.31630

[Global Plotting Config]
 Will create 3 plots.
 Thread count          : 48
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : XXXX
 Pool contract address : XXX
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 4070 Ti
 CUDA Compute Capability   : 8.9
 SM count                  : 60
 Max blocks per SM         : 24
 Max threads per SM        : 1536
 Async Engine Count        : 5
 L2 cache size             : 48.00 MB
 L2 persist cache max size : 36.00 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 11.99 GB
  Free                     : 10.79 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 168443248640 bytes ( 160640.00 MiB or 156.88 GiB )
Total Host RAM required   : 258683772928 bytes ( 246700.07 MiB or 240.92 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

Generating plot 1 / 3: c6ceae09a77fef4d570c958c7efa37edc8679eec413a1d70630fb388bdad4547
Plot temporary file: E:\ChiaBB\plot-k32-2023-03-12-15-02-c6ceae09a77fef4d570c958c7efa37edc8679eec413a1d70630fb388bdad4547.plot.tmp

Generating F1
Finished F1 in 123.57 seconds.
Table 2 completed in 169.84 seconds with 4294893616 entries.
Table 3 completed in 29.11 seconds with 4294742176 entries.
Table 4 completed in 26.20 seconds with 4294505435 entries.
Table 5 completed in 34.58 seconds with 4294005208 entries.
Table 6 completed in 21.17 seconds with 4292887672 entries.
Table 7 completed in 53.94 seconds with 4290737492 entries.
Finalizing Table 7
Finalized Table 7 in 10.09 seconds.
Completed Phase 1 in 468.69 seconds
Marked Table 6 in 9.35 seconds.
Marked Table 5 in 17.08 seconds.
Marked Table 4 in 15.95 seconds.
Marked Table 3 in 59.42 seconds.
Marked Table 2 in 19.91 seconds.
Completed Phase 2 in 121.72 seconds
Compressing Table 1 and 2...
 Step 1 completed step in 112.00 seconds.
 Step 2 completed step in 9.25 seconds.
Completed table 1 in 121.25 seconds with 3429192348 / 4294893616 entries ( 79.84% ).
Compressing tables 2 and 3...
 Step 1 completed step in 3.81 seconds.
 Step 2 completed step in 3.51 seconds.
 Step 3 completed step in 8.96 seconds.
Completed table 2 in 16.28 seconds with 3439485141 / 4294742176 entries ( 80.09% ).
Compressing tables 3 and 4...
 Step 1 completed step in 5.01 seconds.
 Step 2 completed step in 3.49 seconds.
 Step 3 completed step in 8.87 seconds.
Completed table 3 in 17.36 seconds with 3465376160 / 4294505435 entries ( 80.69% ).
Compressing tables 4 and 5...
 Step 1 completed step in 44.05 seconds.
 Step 2 completed step in 3.48 seconds.
 Step 3 completed step in 9.17 seconds.
Completed table 4 in 56.70 seconds with 3531677134 / 4294005208 entries ( 82.25% ).
Compressing tables 5 and 6...
 Step 1 completed step in 53.04 seconds.
 Step 2 completed step in 3.66 seconds.
 Step 3 completed step in 9.00 seconds.
Completed table 5 in 65.70 seconds with 3711341225 / 4292887672 entries ( 86.45% ).
Compressing tables 6 and 7...
 Step 1 completed step in 66.53 seconds.
 Step 2 completed step in 3.81 seconds.
 Step 3 completed step in 17.62 seconds.
Completed table 6 in 87.96 seconds with 4290737492 / 4290737492 entries ( 100.00% ).
Serializing P7 entries
Completed serializing P7 entries in 2.23 seconds.
Completed Phase 3 in 367.49 seconds
Completed Plot 1 in 957.90 seconds ( 15.97 minutes )

E:\ChiaBB\plot-k32-2023-03-12-15-02-c6ceae09a77fef4d570c958c7efa37edc8679eec413a1d70630fb388bdad4547.plot.tmp -> E:\ChiaBB\plot-k32-2023-03-12-15-02-c6ceae09a77fef4d570c958c7efa37edc8679eec413a1d70630fb388bdad4547.plot
Completed writing plot in 14.37 seconds
Final plot table pointers: 
 Table 1:       1288942572 ( 0x000000004cd3b3ec )
 Table 2:      16127572854 ( 0x00000003c1473b76 )
 Table 3:      30108885879 ( 0x0000000702a12377 )
 Table 4:      44195443554 ( 0x0000000a4a40f362 )
 Table 5:      58551506454 ( 0x0000000da1f11616 )
 Table 6:      73637896629 ( 0x00000011252921b5 )
 Table 7:      91079495904 ( 0x0000001534c2d0e0 )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1720396 ( 0x00000000001a404c )
 C 3    :          1720572 ( 0x00000000001a40fc )

Final plot table sizes: 
 Table 1: 14151.22 MiB
 Table 2: 13333.62 MiB
 Table 3: 13433.99 MiB
 Table 4: 13691.01 MiB
 Table 5: 14387.50 MiB
 Table 6: 16633.61 MiB
 Table 7: 16879.36 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1227.59 MiB


Generating plot 2 / 3: cbfed61caa519329aa8b1782924da233f2a6804308156ca07650b86510403048
....
`

**Comment by harold-b** [comment]
@lokus77 if you could provide a full log like the one mech2you provided above, I'd appreciate it. Trying to gather all info I can on this issue.

**Comment by mech2you** [comment]
SystemName="ADAM-PC-THREADR"
OS="Microsoft Windows 10 Pro 10.0.19045"
SystemVendor/Model="Gigabyte Technology Co., Ltd./TRX40 AORUS PRO WIFI"
CPU="AMD Ryzen Threadripper 3960X 24-Core Processor  (C:24|T:48)"
GPU="NVIDIA GeForce RTX 4070 Ti"
GPUSKU="Lovelace"
GPUArch="N/A"
DriverVersion="528.49"
PCIeLink="PCIe 4 x16"
DRAM="256GB, 8x32GB , 2666MT/s"

**Comment by lokus77** [comment]
Hardware: 
-2x Xeon 2650V4  (12c/24T)
-256Gb DDR4 2400CL17 ecc (samsung 8x32gb M386A4G40EM2-CRC  32GB 4DRx4 PC4-2400T-LD2-11  )
-Nvidia Geforce 3080Founder 10Gb Vram conected in Pcie3.0 X16 riser
-Nvme pcie 3.0 samsung 980 pro 1tb
-Huawei RH2288h V3 server (pcie3).

Soft: 
- Windows 10 Pro  22H2  Build 19045.2603  "Windows 10 pro for workstations"
- Nvidia 528.49 drivers. 

Cmd used: 
bladebit_cuda-windows-alpha3.exe -v -c xxxxxxxxxxxxxx -f xxxxxxxxx -z 0 -n 1 -t 8 cudaplot g:/chia

plots in ubuntu 22.10 (kernel 5.19) Alpha1:  About 165 secs
- (XFS) P1 66.83s P2 11.13s P3 87.4s  Copy time 14.92s
Plots in win10:  About 310 secs, or 355s in verbose
- (NTFS) P1 192 P2 34 P3 129 Copy time 9,5s

============
=LOG verbose -v =
============

Bladebit Chia Plotter
Version      : 3.0.0-alpha3-dev
Git Commit   : eb6df030b555fb35addc3d6762424d52826a5d82
Compiled With: msvc 19.33.31630

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 8
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : 93b561exxxxxxxxxxxxxxxxxxxx
 Pool contract address : xch1fxxxxxxxxxxxxxxxxxx
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3080
 CUDA Compute Capability   : 8.6
 SM count                  : 68
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 5
 L2 cache size             : 5.00 MB
 L2 persist cache max size : 3.75 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 10.00 GB
  Free                     : 8.87 GB


Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 168443248640 bytes ( 160640.00 MiB or 156.88 GiB )
Total Host RAM required   : 258683772928 bytes ( 246700.07 MiB or 240.92 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

Generating plot 1 / 1: 3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13
Plot temporary file: g:/chia/plot-k32-2023-03-13-22-27-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot.tmp

Generating F1
Finished F1 in 2.92 seconds.
Table 2 completed in 8.44 seconds with 4294927287 entries.
Table 3 completed in 37.03 seconds with 4294801213 entries.
Table 4 completed in 35.40 seconds with 4294532457 entries.
Table 5 completed in 36.03 seconds with 4294092532 entries.
Table 6 completed in 31.72 seconds with 4293202019 entries.
Table 7 completed in 26.73 seconds with 4291433858 entries.
Finalizing Table 7
Finalized Table 7 in 13.61 seconds.
Completed Phase 1 in 192.19 seconds
Marked Table 6 in 6.93 seconds.
Marked Table 5 in 6.67 seconds.
Marked Table 4 in 6.62 seconds.
Marked Table 3 in 6.85 seconds.
Marked Table 2 in 6.95 seconds.
Completed Phase 2 in 34.03 seconds
Compressing Table 1 and 2...
 Step 1 completed step in 7.81 seconds.
 Step 2 completed step in 9.11 seconds.
Completed table 1 in 16.92 seconds with 3429245768 / 4294927287 entries ( 79.84% ).
Compressing tables 2 and 3...
 Step 1 completed step in 6.27 seconds.
 Step 2 completed step in 6.07 seconds.
 Step 3 completed step in 8.98 seconds.
Completed table 2 in 21.33 seconds with 3439548453 / 4294801213 entries ( 80.09% ).
Compressing tables 3 and 4...
 Step 1 completed step in 6.18 seconds.
 Step 2 completed step in 6.10 seconds.
 Step 3 completed step in 9.04 seconds.
Completed table 3 in 21.32 seconds with 3465446598 / 4294532457 entries ( 80.69% ).
Compressing tables 4 and 5...
 Step 1 completed step in 5.95 seconds.
 Step 2 completed step in 6.19 seconds.
 Step 3 completed step in 9.06 seconds.
Completed table 4 in 21.21 seconds with 3531853268 / 4294092532 entries ( 82.25% ).
Compressing tables 5 and 6...
 Step 1 completed step in 5.96 seconds.
 Step 2 completed step in 6.42 seconds.
 Step 3 completed step in 9.39 seconds.
Completed table 5 in 21.76 seconds with 3711682334 / 4293202019 entries ( 86.45% ).
Compressing tables 6 and 7...
 Step 1 completed step in 6.00 seconds.
 Step 2 completed step in 7.11 seconds.
 Step 3 completed step in 10.42 seconds.
Completed table 6 in 23.54 seconds with 4291433858 / 4291433858 entries ( 100.00% ).
Serializing P7 entries
Completed serializing P7 entries in 3.00 seconds.
Completed Phase 3 in 129.10 seconds
Completed Plot 1 in 355.32 seconds ( 5.92 minutes )

g:/chia/plot-k32-2023-03-13-22-27-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot.tmp -> g:/chia/plot-k32-2023-03-13-22-27-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot
Completed writing plot in 9.43 seconds
Final plot table pointers:
 Table 1:       1289152852 ( 0x000000004cd6e954 )
 Table 2:      16128013546 ( 0x00000003c14df4ea )
 Table 3:      30109584646 ( 0x0000000702abcd06 )
 Table 4:      44196425371 ( 0x0000000a4a4fee9b )
 Table 5:      58553204221 ( 0x0000000da20afdfd )
 Table 6:      73640976346 ( 0x0000001125581fda )
 Table 7:      91085406121 ( 0x00000015351cffa9 )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1720676 ( 0x00000000001a4164 )
 C 3    :          1720852 ( 0x00000000001a4214 )

Final plot table sizes:
 Table 1: 14151.44 MiB
 Table 2: 13333.87 MiB
 Table 3: 13434.26 MiB
 Table 4: 13691.69 MiB
 Table 5: 14388.82 MiB
 Table 6: 16636.30 MiB
 Table 7: 16882.10 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1227.79 MiB

**Comment by harold-b** [comment]
Can you guys try creating a compressed level 1 `-z 1` plot, please? You can then run the simulator against it or I think the `validate` command ought to work fine as well, as long as you don't use `-u`.

I am trying to determine if it's happening w/ compressed as well. Only common denominator I see so far is 256G of RAM

**Comment by harold-b** [comment]
I am still unable to reproduce anything on my side, using the same published alpha3 executable. I used your plot id, @lokus77 and got the same output:

```bash
...
Serializing P7 entries
Completed serializing P7 entries in 2.03 seconds.
Completed Phase 3 in 86.85 seconds
Completed Plot 1 in 205.53 seconds ( 3.43 minutes )

D:/plot-k32-2023-03-13-18-40-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot.tmp -> D:/plot-k32-2023-03-13-18-40-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot
Completed writing plot in 5.74 seconds
Final plot table pointers:
 Table 1:       1289152852 ( 0x000000004cd6e954 )
 Table 2:      16128013546 ( 0x00000003c14df4ea )
 Table 3:      30109584646 ( 0x0000000702abcd06 )
 Table 4:      44196425371 ( 0x0000000a4a4fee9b )
 Table 5:      58553204221 ( 0x0000000da20afdfd )
 Table 6:      73640976346 ( 0x0000001125581fda )
 Table 7:      91085406121 ( 0x00000015351cffa9 )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1720676 ( 0x00000000001a4164 )
 C 3    :          1720852 ( 0x00000000001a4214 )

Final plot table sizes:
 Table 1: 14151.44 MiB
 Table 2: 13333.87 MiB
 Table 3: 13434.26 MiB
 Table 4: 13691.69 MiB
 Table 5: 14388.82 MiB
 Table 6: 16636.30 MiB
 Table 7: 16882.10 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1227.79 MiB

```

But the validation looks good on mine:
```bash
[ 33]     228428..235347     ( 0.03% ) C3 Park Validated in 10.70 seconds | Proofs Failed: 0
[ 49]     339173..346091     ( 0.03% ) C3 Park Validated in 10.73 seconds | Proofs Failed: 0
[ 35]     242272..249191     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[  1]       6924..13843      ( 0.03% ) C3 Park Validated in 10.73 seconds | Proofs Failed: 0
[ 31]     214584..221503     ( 0.03% ) C3 Park Validated in 10.71 seconds | Proofs Failed: 0
[ 26]     179974..186893     ( 0.03% ) C3 Park Validated in 10.71 seconds | Proofs Failed: 0
[ 30]     207662..214581     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 14]      96910..103829     ( 0.03% ) C3 Park Validated in 10.71 seconds | Proofs Failed: 0
[  9]      62300..69219      ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 29]     200740..207659     ( 0.03% ) C3 Park Validated in 10.73 seconds | Proofs Failed: 0
[ 40]     276882..283801     ( 0.03% ) C3 Park Validated in 10.70 seconds | Proofs Failed: 0
[ 23]     159208..166127     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 37]     256116..263035     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 52]     359936..366854     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 16]     110754..117673     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 50]     346094..353012     ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 12]      83066..89985      ( 0.03% ) C3 Park Validated in 10.72 seconds | Proofs Failed: 0
[ 20]     138442..145361     ( 0.03% ) C3 Park Validated in 10.75 seconds | Proofs Failed: 0
[  0]          2..6921       ( 0.03% ) C3 Park Validated in 10.80 seconds | Proofs Failed: 0
[ 44]     304568..311486     ( 0.03% ) C3 Park Validated in 10.77 seconds | Proofs Failed: 0
[ 59]     408383..415301     ( 0.03% ) C3 Park Validated in 11.03 seconds | Proofs Failed: 0
[ 19]     131521..138439     ( 0.04% ) C3 Park Validated in 7.26 seconds | Proofs Failed: 0
...
```

**Comment by lokus77** [comment]
Z1 plot

bladebit_cuda-windows-alpha3.exe -v -c xxxxxxxx -f xxxxxxxx **-z 1** -n 1 -t 8 cudaplot g:/chia

Bladebit Chia Plotter
Version      : 3.0.0-alpha3-dev
Git Commit   : eb6df030b555fb35addc3d6762424d52826a5d82
Compiled With: msvc 19.33.31630

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 8
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Compression Level     : 1
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3080
 CUDA Compute Capability   : 8.6
 SM count                  : 68
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 5
 L2 cache size             : 5.00 MB
 L2 persist cache max size : 3.75 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 10.00 GB
  Free                     : 8.87 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 141733920768 bytes ( 135168.00 MiB or 132.00 GiB )
Total Host RAM required   : 231974445056 bytes ( 221228.07 MiB or 216.04 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

Generating plot 1 / 1: caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b
Plot temporary file: g:/chia/plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot.tmp

Generating F1
Finished F1 in 2.85 seconds.
Table 2 completed in 10.79 seconds with 4294940352 entries.
Table 3 completed in 12.30 seconds with 4294828493 entries.
Table 4 completed in 34.84 seconds with 4294664198 entries.
Table 5 completed in 33.87 seconds with 4294276894 entries.
Table 6 completed in 29.84 seconds with 4293471970 entries.
Table 7 completed in 24.96 seconds with 4292032633 entries.
Finalizing Table 7
Finalized Table 7 in 12.93 seconds.
Completed Phase 1 in 162.67 seconds
Marked Table 6 in 7.24 seconds.
Marked Table 5 in 7.01 seconds.
Marked Table 4 in 6.81 seconds.
Marked Table 3 in 6.46 seconds.
Completed Phase 2 in 27.52 seconds
Compressing Table 2 and 3...
 Step 1 completed step in 7.29 seconds.
 Step 2 completed step in 7.86 seconds.
Completed table 2 in 15.15 seconds with 3439643097 / 4294828493 entries ( 80.09% ).
Compressing tables 3 and 4...
 Step 1 completed step in 5.86 seconds.
 Step 2 completed step in 6.08 seconds.
 Step 3 completed step in 8.35 seconds.
Completed table 3 in 20.30 seconds with 3465632385 / 4294664198 entries ( 80.70% ).
Compressing tables 4 and 5...
 Step 1 completed step in 6.17 seconds.
 Step 2 completed step in 6.16 seconds.
 Step 3 completed step in 8.51 seconds.
Completed table 4 in 20.84 seconds with 3532069601 / 4294276894 entries ( 82.25% ).
Compressing tables 5 and 6...
 Step 1 completed step in 6.31 seconds.
 Step 2 completed step in 6.39 seconds.
 Step 3 completed step in 8.85 seconds.
Completed table 5 in 21.56 seconds with 3711988308 / 4293471970 entries ( 86.46% ).
Compressing tables 6 and 7...
 Step 1 completed step in 6.33 seconds.
 Step 2 completed step in 7.08 seconds.
 Step 3 completed step in 9.81 seconds.
Completed table 6 in 23.22 seconds with 4292032633 / 4292032633 entries ( 100.00% ).
Serializing P7 entries
Completed serializing P7 entries in 2.98 seconds.
Completed Phase 3 in 104.07 seconds
Completed Plot 1 in 294.27 seconds ( 4.90 minutes )

g:/chia/plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot.tmp -> g:/chia/plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot
Completed writing plot in 4.94 seconds
Final plot table pointers:
 Table 1:                0 ( 0x0000000000000000 )
 Table 2:       1289333092 ( 0x000000004cd9a964 )
 Table 3:      15289761796 ( 0x000000038f574004 )
 Table 4:      29377360096 ( 0x00000006d706f0e0 )
 Table 5:      43735021396 ( 0x0000000a2ecf7754 )
 Table 6:      58824042271 ( 0x0000000db22fa71f )
 Table 7:      76270911271 ( 0x00000011c219bf27 )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1720916 ( 0x00000000001a4254 )
 C 3    :          1721092 ( 0x00000000001a4304 )

Final plot table sizes:
 Table 1: 0.00 MiB
 Table 2: 13351.85 MiB
 Table 3: 13434.98 MiB
 Table 4: 13692.53 MiB
 Table 5: 14390.01 MiB
 Table 6: 16638.63 MiB
 Table 7: 16884.46 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1227.96 MiB


***************************
**Validations:** 

I've tried to test it with: 

bladebit_cuda-windows-alpha3.exe -t 12 validate -m G:/chia/z1/plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot
Reading plot file into memory...

but i cant see in taskmanager any is reading the file in G disk.
8 of my 48 threads get 100% ussage  but does not show more info, it stay in:

Validating plot G:/chia/z1/plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot
K               : 32
Unpacked        : false
Maximum C3 Parks: 429204

[  0] Park range:          0..35767       Park count: 35767
[  2] Park range:      71534..107301      Park count: 35767
[  4] Park range:     143068..178835      Park count: 35767
[ 11] Park range:     393437..429204      Park count: 35767
[  7] Park range:     250369..286136      Park count: 35767
[ 10] Park range:     357670..393437      Park count: 35767
[  6] Park range:     214602..250369      Park count: 35767
[  8] Park range:     286136..321903      Park count: 35767
[  3] Park range:     107301..143068      Park count: 35767
[  5] Park range:     178835..214602      Park count: 35767
[  1] Park range:      35767..71534       Park count: 35767
[  9] Park range:     321903..357670      Park count: 35767

does not show more text after +5 mins. Still testing.


-----
With Chia plots check:
The Z0 plot from log on top: 

chia plots check -n 50
2023-03-14T00:38:59.097  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_manager loading code (parallel read: True)

2023-03-14T00:38:59.207  chia.plotting.cache              : INFO     Loaded 427834 bytes of cached data
2023-03-14T00:38:59.363  chia.plotting.cache              : INFO     Parsed 564 cache entries in 0.16s
2023-03-14T00:38:59.425  chia.plotting.check_plots        : INFO     event: started, loaded 0 plots, 1 remaining
2023-03-14T00:38:59.425  chia.plotting.manager            : WARNING  Plot G:\chia\z0\plot-k32-2023-03-13-22-27-2023-03-14T00:38:59.425  chia.plotting.check_plots        : INFO     event: batch_processed, loaded 1 plots, 0 remaining
2023-03-14T00:38:59.425  chia.plotting.check_plots        : INFO     event: done, loaded 1 plots, 0 remaining
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO     Starting to test each plot with 50 challenges each
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO     Testing plot G:\chia\z0\plot-k32-2023-03-13-22-27-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot k=32
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO        Pool contract address:  xch1fqq6pzznk0fcda6cnejayv9lXXXXXXXXXXX
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO        Farmer public key:      93b561e3666f2776d446fb4237fa5bXXXXXXXXXXXXXXX
2023-03-14T00:39:00.441  chia.plotting.check_plots        : INFO        Local sk:               <PrivateKey 5b7ab83e63db6c70f06fe06ee29XXXXXXXXXXXXXX>
2023-03-14T00:39:00.472  chia.plotting.check_plots        : ERROR       Proofs 0 / 50, 0.0
2023-03-14T00:39:00.472  chia.plotting.check_plots        : INFO
2023-03-14T00:39:00.472  chia.plotting.check_plots        : INFO
2023-03-14T00:39:00.472  chia.plotting.check_plots        : INFO     Summary
2023-03-14T00:39:00.472  chia.plotting.check_plots        : INFO     Found 0 valid plots, total size 0.00000 TiB
2023-03-14T00:39:00.472  chia.plotting.check_plots        : WARNING  1 invalid plots found:
2023-03-14T00:39:00.472  chia.plotting.check_plots        : WARNING      1 bad plots:
2023-03-14T00:39:00.472  chia.plotting.check_plots        : WARNING  G:\chia\z0\plot-k32-2023-03-13-22-27-3d6a764cd3ba1be7fd28215e6db12e8850b43ea92af0d836dae94771a5a25e13.plot

The Z1  plot log.  Normal error: Standard chia/harvester does not recognize compressed plots.

chia plots check -n 50
2023-03-14T00:45:03.051  chia.plotting.check_plots        : INFO     Loading plots in config.yaml using plot_manager loading code (parallel read: True)

2023-03-14T00:45:03.160  chia.plotting.cache              : INFO     Loaded 427834 bytes of cached data
2023-03-14T00:45:03.300  chia.plotting.cache              : INFO     Parsed 564 cache entries in 0.14s
2023-03-14T00:45:03.363  chia.plotting.check_plots        : INFO     event: started, loaded 0 plots, 1 remaining
2023-03-14T00:45:03.379  chia.plotting.manager            : ERROR    Failed to open file G:\chia\z1\plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot. Invalid plot header magic Traceback (most recent call last):
  File "chia\plotting\manager.py", line 274, in process_file
ValueError: Invalid plot header magic

2023-03-14T00:45:03.379  chia.plotting.check_plots        : INFO     event: batch_processed, loaded 0 plots, 0 remaining
2023-03-14T00:45:03.379  chia.plotting.check_plots        : INFO     event: done, loaded 0 plots, 0 remaining
2023-03-14T00:45:04.394  chia.plotting.check_plots        : INFO
2023-03-14T00:45:04.394  chia.plotting.check_plots        : INFO
2023-03-14T00:45:04.394  chia.plotting.check_plots        : INFO     Summary
2023-03-14T00:45:04.394  chia.plotting.check_plots        : INFO     Found 0 valid plots, total size 0.00000 TiB
2023-03-14T00:45:04.394  chia.plotting.check_plots        : WARNING  1 invalid plots found:
2023-03-14T00:45:04.394  chia.plotting.check_plots        : WARNING      1 unopenable plots:
2023-03-14T00:45:04.394  chia.plotting.check_plots        : WARNING  G:\chia\z1\plot-k32-c01-2023-03-14-00-20-caf327b4f5d96e452afae7749ef105c5035181bcff0d2275df04df60b63afa7b.plot

**Comment by harold-b** [comment]
Thank you for taking the time to get me this info. Does querying a few f7 result in challenges from a compressed plot?
Could you try `validate --f7 <value> <path_to_compressed_plot>` where `<value>` is a number between `0` and `1^32`. It's normal for it to return a message like "f7 not found". But if it has an error looking it up, it will exit with an error. You could try fetching a few (maybe around 0-20)?

I spent all day yesterday experimenting on windows to no avail. All plots continue to come out valid on my side, however I am on windows 11. I might try setting up a windows 10 machine. 
Downgrading to 256G of RAM also did not yield any issues, so it seems like it is not related to that.

As table entry count and pruned entry count appear to be exactly the same when I use one of your plot ids, it seems like the issue happens at the very end during phase 3, at the point of compressing to parks plot serialization. However, I've no findings yet. I apologize for the inconvenience.

**Comment by harold-b** [comment]
Like that yes. But could you try with a sequence from 0-20? It ought to at least have 1. If you get the same error from `0-20`, then this might indicate that the C tables are the ones that are corrupted.

**Comment by kinomexanik** [comment]
Installed windows 11 and alpha 3 and was pleasantly surprised. Plots are valid. A great reason to switch to w11.

**Comment by harold-b** [comment]
Well that's the second confirmation today we've got that plots under win11 work fine. I will have to indeed investigate on a win10 machine

**Comment by lokus77** [comment]
Could not find f7 1 in plot.
Could not find f7 2 in plot.
Could not find f7 3 in plot.
Could not find f7 4 in plot.
Could not find f7 5 in plot.
Could not find f7 6 in plot.
Could not find f7 7 in plot.
Could not find f7 8 in plot.
Could not find f7 9 in plot.
Could not find f7 10 in plot.
Could not find f7 11 in plot.
Could not find f7 12 in plot.
Could not find f7 13 in plot.
Could not find f7 14 in plot.
Could not find f7 15 in plot.
Could not find f7 16 in plot.
Could not find f7 17 in plot.
Could not find f7 18 in plot.
Could not find f7 19 in plot.
Could not find f7 20 in plot.
Could not find f7 21 in plot.
Could not find f7 22 in plot.
Could not find f7 23 in plot.
Could not find f7 24 in plot.
Could not find f7 25 in plot.

**Comment by harold-b** [comment]
That should be enough for now, I appreciate it. At the very least the C tables (initially written to plot file right after phase 1), are faulty.

**Comment by kinomexanik** [comment]
Microsoft Windows Server 2019 Datacenter 17763.4131 is bad plots

**Comment by lokus77** [comment]
> That should be enough for now, I appreciate it. At the very least the C tables (initially written to plot file right after phase 1), are faulty.

I've updated to Windows 11. 
Same scripts/keys.
Z0 uncompressed plots are Valid
Z1 compressed plots are Valid

(I have yet win10 in another SSD if you need some more test)

**Comment by SSayman** [comment]
BBC Validate -m /x/x.plot
Park (xxxxx) proof fetch failed for f7 (xxxxxxx) local (0) = xxxxxxx (0x000000 ...

Compressed Plots C6 & C7 the same output.

Ubuntu 22.1

**Comment by gibblinhimer** [comment]
I have a slightly different validation error...

created one compressed plot on a Linux machine with compression level 7 (-z 7) then moved that file into my current plots directory with some uncompressed plots.

when I ran - chia plots check -g xxxxx    --- chia blew an error. (Invalid plot header magic Traceback)

Does the newest non-beta release of chia not support farming compressed plots yet?

Side note.. I have one full node server that runs the full node and farmer.
and 2 harvester servers that have the plots and run the harvester only... the chia check plots was run on the harvester.
all my servers are Linux machines.

bladebit validation runs just fine

**Comment by corymiranda** [comment]
No, current Chia releases do not support farming compressed plots.

**Comment by mech2you** [comment]
Have somebody testet to create a plot in Linux and valdiate it on windows 10? I have no resources for this test... Maybe the plots on windows are good and the probleme is the validation.

**Comment by kinomexanik** [comment]
In Linux, the made plots are valid, and are checked in Windows. The problem is that the plots made in windows (except w11) are bad.

**Comment by SSayman** [comment]
i also use Linux and when i Validate , i came out ( proof fetch failed for f7 ) so how we know these plots are valid?

**Comment by kinomexanik** [comment]
share a beta that supports already compressed plots

**Comment by harold-b** [comment]
> share a beta that supports already compressed plots

There's an alpha build for compressed CPU farming available in the [beta program](https://docs.google.com/forms/d/e/1FAIpQLSdc54puHFtpatrkY-tnCT0CO2cGiYWzZ23IiKVhbXvkIt_17A/viewform).

**Comment by SSayman** [comment]
I build my Farm since Febuary 2023 and cant wait to fill 274 TB with Compressed Plots!
@harold-b Will erveryone get the Chance to use the beta programm ?
Thank you!
S.S

**Comment by harold-b** [comment]
Yes, you can sign up on the link I posted above. Everything is open source, so anyone can build it themselves also.

Please keep in mind that we're still in alpha stage, so things may be subject to change. Meaning, some parameters might still change for generating compressed plots, rendering old ones incompatible if we do.

**Comment by SSayman** [comment]
Yes, that would be a risk to plot all 274tb but for testing a good experience!
Thank you @harold-b

**Comment by mech2you** [comment]
Upgrade to Win 11 an the problem near the same. 
SystemInfo.ps1
SystemName="ADAM-PC-THREADR"
OS="Microsoft Windows 11 Pro 10.0.22621"
SystemVendor/Model="Gigabyte Technology Co., Ltd./TRX40 AORUS PRO WIFI"
CPU="AMD Ryzen Threadripper 3960X 24-Core Processor  (C:24|T:48)"
GPU="NVIDIA GeForce RTX 4070 Ti"
GPUSKU="Lovelace"
GPUArch="N/A"
DriverVersion="531.18"
PCIeLink="PCIe 4 x16"
DRAM="256GB, 8x32GB , 2666MT/s"
______PLOTTER____________________________________________________________________________________________
bladebit_cuda-windows-alpha3.exe -n 1 --compress 1 -f XXX-c XXX cudaplot E:\ChiaBB\

Bladebit Chia Plotter
Version      : 3.0.0-alpha3-dev
Git Commit   : eb6df030b555fb35addc3d6762424d52826a5d82
Compiled With: msvc 19.33.31630

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 48
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : XXX
 Pool contract address : XXX
 Compression Level     : 1
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 4070 Ti
 CUDA Compute Capability   : 8.9
 SM count                  : 60
 Max blocks per SM         : 24
 Max threads per SM        : 1536
 Async Engine Count        : 1
 L2 cache size             : 48.00 MB
 L2 persist cache max size : 36.00 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 11.99 GB
  Free                     : 10.79 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 141733920768 bytes ( 135168.00 MiB or 132.00 GiB )
Total Host RAM required   : 231974445056 bytes ( 221228.07 MiB or 216.04 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

Generating plot 1 / 1: 2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336
Plot temporary file: E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot.tmp

Generating F1
Finished F1 in 1.58 seconds.
Table 2 completed in 6.75 seconds with 4294936110 entries.
Table 3 completed in 13.36 seconds with 4294765578 entries.
Table 4 completed in 18.78 seconds with 4294456622 entries.
Table 5 completed in 19.33 seconds with 4293906061 entries.
Table 6 completed in 16.59 seconds with 4292858500 entries.
Table 7 completed in 14.38 seconds with 4290826955 entries.
Finalizing Table 7
Finalized Table 7 in 8.00 seconds.
Completed Phase 1 in 98.92 seconds
Marked Table 6 in 4.78 seconds.
Marked Table 5 in 4.39 seconds.
Marked Table 4 in 4.30 seconds.
Marked Table 3 in 4.28 seconds.
Completed Phase 2 in 17.76 seconds
Compressing Table 2 and 3...
 Step 1 completed step in 4.99 seconds.
 Step 2 completed step in 4.99 seconds.
Completed table 2 in 9.98 seconds with 3439506529 / 4294765578 entries ( 80.09% ).
Compressing tables 3 and 4...
 Step 1 completed step in 4.54 seconds.
 Step 2 completed step in 4.90 seconds.
 Step 3 completed step in 5.38 seconds.
Completed table 3 in 14.82 seconds with 3465338506 / 4294456622 entries ( 80.69% ).
Compressing tables 4 and 5...
 Step 1 completed step in 4.52 seconds.
 Step 2 completed step in 4.94 seconds.
 Step 3 completed step in 5.44 seconds.
Completed table 4 in 14.90 seconds with 3531610124 / 4293906061 entries ( 82.25% ).
Compressing tables 5 and 6...
 Step 1 completed step in 4.56 seconds.
 Step 2 completed step in 5.04 seconds.
 Step 3 completed step in 5.66 seconds.
Completed table 5 in 15.26 seconds with 3711306813 / 4292858500 entries ( 86.45% ).
Compressing tables 6 and 7...
 Step 1 completed step in 4.59 seconds.
 Step 2 completed step in 5.36 seconds.
 Step 3 completed step in 6.29 seconds.
Completed table 6 in 16.25 seconds with 4290826955 / 4290826955 entries ( 100.00% ).
Serializing P7 entries
Completed serializing P7 entries in 2.17 seconds.
Completed Phase 3 in 73.38 seconds
Completed Plot 1 in 190.06 seconds ( 3.17 minutes )

E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot.tmp -> E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Completed writing plot in 4.65 seconds
Final plot table pointers: 
 Table 1:                0 ( 0x0000000000000000 )
 Table 2:       1288969608 ( 0x000000004cd41d88 )
 Table 3:      15288839800 ( 0x000000038f492e78 )
 Table 4:      29375239300 ( 0x00000006d6e69484 )
 Table 5:      43731035800 ( 0x0000000a2e92a698 )
 Table 6:      58817284450 ( 0x0000000db1c88962 )
 Table 7:      76259250025 ( 0x00000011c167cf69 )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1720432 ( 0x00000000001a4070 )
 C 3    :          1720608 ( 0x00000000001a4120 )

Final plot table sizes: 
 Table 1: 0.00 MiB
 Table 2: 13351.32 MiB
 Table 3: 13433.84 MiB
 Table 4: 13690.75 MiB
 Table 5: 14387.37 MiB
 Table 6: 16633.95 MiB
 Table 7: 16879.72 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1227.62 MiB
__________________________________________________________________________________________________

PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe -t 4 validate -m  E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Reading plot file into memory...
Validating plot E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
K               : 32
Unpacked        : false
Maximum C3 Parks: 429083

[  0] Park range:          0..107271      Park count: 107271
[  3] Park range:     321813..429083      Park count: 107270
[  1] Park range:     107271..214542      Park count: 107271
[  2] Park range:     214542..321813      Park count: 107271
[  0] Park 0 proof fetch failed for f7[127] local(127) = 125 ( 0x000000000000007d )
[  2] Park 214542 proof fetch failed for f7[2145420368] local(368) = 2147475932 ( 0x000000007fffe1dc )
[  1] Park 107271 proof fetch failed for f7[1072711197] local(1197) = 1073747381 ( 0x00000000400015b5 )
______________________________________________________________________________________________________
after 1 hour i abortet this

PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe -t 4 validate -m  --f7 1 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe -t 4 validate -m --f7 1 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe -t 4 validate -m --f7 2 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe -t 4 validate --f7 2 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 2 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 3 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 4 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 5 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 5 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 6 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 7 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 8 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 8 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 9 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 10 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 10 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 11 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 11 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 12 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 13 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 14 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 15 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 15 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 16 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 17 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 17 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 18 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
Could not find f7 18 in plot.
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 19 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads> .\bladebit_cuda-windows-alpha3.exe validate --f7 20 E:\ChiaBB\plot-k32-c01-2023-03-18-13-26-2753974b49bdafafcecfd5f834ac37b10bb1a732476b287543c1ff050a8f4336.plot
PS C:\Users\micro\Downloads>

**Comment by kinomexanik** [comment]
I checked the old plots made by MM, there is also an if the --f7 parameter is up to 20 (Could not find f7 13 in plot)

**Comment by kinomexanik** [comment]
Now plots made in Windows 11 send proofs to the pool. Everything is fine.

**Comment by kinomexanik** [comment]
**bladebit_cuda-windows-alpha3.exe validate --f7 123** C:\hdd\18tbSegSAS\bb\plot-k32-2023-03-16-03-06-3a76176d8b31b63831b66d2d44a9bd1ee8c2de4d68a0d101e9ab6a705a1a0906.plot
64f250e4d4e39dfbf228d261f4a1fa84e204284653f8fc81926b9034041351311fe4559c702753214039a4826cae1226c1c0e6706fd6dcdbe0ae2da96ae1c622da3e299e5c1df6ad6d81035a02ff4f59c3fa468c8c17bb26ca83789925e225b52a96bc9c4e47732fe3d65dfdd282d232f08df31792d95b1b30b3d0f5ff400b951a19c74a84f6c388bef0e53177da2eb39db52b14c0e977badaf136502233edc53a33a43aa582b747b3b5fd7c8bf51f9ad7cf97a53924830df5f7610ca26cd25fbc13fdfce3031dea3eb7b35cdc0daf6ac16e9b36e7ccf2a1f9e6d7098a10a5f45ced640935ee569c2b14222b663aaa00e03f939bda7dda45f40992523d0a9bd8

**Comment by kinomexanik** [comment]
**bladebit_cuda-windows-alpha3.exe validate --f7 13** C:\hdd\18tbSegSAS\bb\plot-k32-2023-03-16-03-06-3a76176d8b31b63831b66d2d44a9bd1ee8c2de4d68a0d101e9ab6a705a1a0906.plot
Could not find f7 13 in plot.

**Comment by kinomexanik** [comment]
**bladebit_cuda-windows-alpha3.exe validate --f7 13** C:\hdd\18tbWD1\mm\plot-k32-2023-02-04-10-31-d4dacf936a6c6349105e8f0145960180a3774bfadba08e49120c7b8388ac5703.plot
Could not find f7 13 in plot.

**Comment by BookSwapSteve** [comment]
I see this is somewhat of an old thread, but the problem appears to be persisting for Windows even in the newer builds.

I'm seeing all my compressed plots (c7) being invalid even with the latest 4.3 alpha on Windows Server 2019. No errors when plotting, no errors when harvesting them with the v2 alpha software, but they all fail the plot check and are noticeably absent from pooling stats. Stupidly I plotted about 24 18TB disks before doing the plot check, not a good plot among them.

Switched the machine over to Linux and it's creating valid plots.

I've also commented on this in the bladebit-alpha discord channel (same username), hopefully not many people as silly as me! It's easy to think the problems was fixed and bladebit would be making valid plots on Windows as the last comment on here being nearly 3 months ago, and new builds for Windows are being pushed out.

The machine is "dual boot" (sadly that it involves changing cables and that involves getting it out of a rack), but if you would like me to try some things out or need some extra information let me know.

**Comment by RnMss** [comment]
By now (alpha 4.3), still occurs on some Windows 10.

**Comment by harold-b** [comment]
Work is being done on the disk hybrid that might fix this. Unfortunately we are still not able to reproduce on our machines, but hopefully soon when we have the code ready some folks can test on machines where the issue does occur to see if it is solves it. 

I appreciate the patience you've all have had.

**Comment by RDReindeer** [comment]
Hello, is there a solution to this problem now, I upgraded to win11 and still can't p out the effective field

**Comment by brause** [comment]
Would love too see this fixed.
